# Generated by Django 4.1.7 on 2023-03-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_iser',
            new_name='id_user',
        ),
    ]
